node {
    
    stage('Checkout'){
        deleteDir();
        checkout scm;
    }
    
    stage('Stop stack dev-api'){
        sh 'docker stack ls | grep "workflow" -v | grep "dev-back" -v | grep "dev-front" -v | grep "preprod" -v | grep "prod" -v | awk -F " " \'{ if (NR>1) print $1 }\' | xargs docker stack kill | xargs docker stack rm || true'
        sh 'docker stack ls | grep "workflow" -v | grep "dev-back" -v | grep "dev-front" -v | grep "preprod" -v | grep "prod" -v | awk -F " " \'{ if (NR>1) print $1 }\' | xargs docker stack rm || true'
    }

    stage('Build image dev-api'){
        // imageapi     = docker.build("dev-api", "--no-cache -f docker/dev-server/Dockerfile --target test .");
        imageapi     = docker.build("dev-api", "-f docker/dev-server/Dockerfile .");
    }

    stage('Publish to Nexus Repository Manager'){
        sh 'docker tag dev-api:latest repo.dsp-archiwebo20-db-od-sn-bm.fr/dev-api:latest'
        sh 'docker login --username jenkins-user --password jenkins  repo.dsp-archiwebo20-db-od-sn-bm.fr'
        sh 'docker push repo.dsp-archiwebo20-db-od-sn-bm.fr/dev-api:latest'
    }

    stage('Deploy stack dev-api'){
        sh 'docker login --username jenkins-user --password jenkins repo.dsp-archiwebo20-db-od-sn-bm.fr'
        sh 'docker stack deploy --with-registry-auth --compose-file docker/dev-server/docker-compose.yml dev-api'
    }
    
}